org.gradle.jvmargs=-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx2048m -Dkotlin.incremental=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.skip.compiler.on.dependency.change=false -Djava.util.UUID.ENABLE_STRICT_VALIDATION=false
systemProp.file.encoding=UTF-8

# Use this to specify the version of the Android Gradle Plugin to use.
# For example, AGP_VERSION=7.3.0
AGP_VERSION=9.0.0

# Project-wide Android settings.
# Used by build.gradle files.
TARGET_SDK_VERSION=34
MIN_SDK_VERSION=21

# Project-wide version codes.
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0.0

# AyuGram settings
AYU_CONFIG_FILE=config/debug/app_config.json
AYU_BUILD_CONFIG_FILE=config/debug/build_config.json
AYU_BUILD_CONFIG_FILE_RELEASE=config/release/build_config.json

# Keep this file in project root if you want to use build-in update function
# if not - delete it (or change the value below to false)
AYU_CHECK_UPDATES=true
